// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektZaliczeniowyASP.NET.Data;

#nullable disable

namespace ProjektZaliczeniowyASP.NET.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("ProjektZaliczeniowyASP.NET.Models.KursModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kursy");
                });

            modelBuilder.Entity("ProjektZaliczeniowyASP.NET.Models.StudentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Studenci");
                });

            modelBuilder.Entity("ProjektZaliczeniowyASP.NET.Models.ZapisNaKursModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("TEXT");

                    b.Property<int>("KursId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KursId");

                    b.HasIndex("StudentId");

                    b.ToTable("ZapisyNaKurs");
                });

            modelBuilder.Entity("ProjektZaliczeniowyASP.NET.Models.ZapisNaKursModel", b =>
                {
                    b.HasOne("ProjektZaliczeniowyASP.NET.Models.KursModel", "Kurs")
                        .WithMany("ZapisaniStudenci")
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektZaliczeniowyASP.NET.Models.StudentModel", "Student")
                        .WithMany("ZapisaneKursy")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurs");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ProjektZaliczeniowyASP.NET.Models.KursModel", b =>
                {
                    b.Navigation("ZapisaniStudenci");
                });

            modelBuilder.Entity("ProjektZaliczeniowyASP.NET.Models.StudentModel", b =>
                {
                    b.Navigation("ZapisaneKursy");
                });
#pragma warning restore 612, 618
        }
    }
}
